# -------------------------------
# Copyright (c) by fitomaks 2022
# -------------------------------

name: Build_Banking_project

on:
  push:
    branches:
      - main
      
  Coveralls:
    runs-on: ubuntu-latest
    
    steps:
      - name: Git clone my repo
        uses: actions/checkout@v1 
        
      - name : Prepare environment
        shell: bash
        run  : |
          git submodule update --init --recursive
          sudo apt install lcov
          
      - name: Build system of tests with --coverage
        run : |
          mkdir build && cd build
          cmake -DCOVERAGE=1 ..
          make
          ./tests
          
      - name: Create lcov.info
        run : |
          cd build
          lcov --capture --directory . --output-file lcov.info --test-name tests
          
      - name: Coveralls.io
        uses: coverallsapp/github-action@master
        with:
          github-token      : ${{ secrets.GITHUB_TOKEN }}
          path-to-lcov      : ./cmake/lcov.info
          coveralls-endpoint: https://coveralls.io
